# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fri_ws_web', '0002_auto_20161211_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('edit_article', 'Can edit the article'),)},
        ),
    ]
