# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0008_paneli_tip_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='soba',
            name='namembnost',
            field=models.IntegerField(null=True),
        ),
    ]
