# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0011_stanovanje_merilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soba',
            name='namembnost',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
