# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanovanje',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='stanovanje',
            name='comment',
        ),
        migrations.AddField(
            model_name='stanovanje',
            name='izolacija_sten',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stanovanje',
            name='izolacija_tal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stanovanje',
            name='nacin_montaze',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stanovanje',
            name='st_sten',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stanovanje',
            name='temp_primanlkjaj',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stanovanje',
            name='visina_stropa',
            field=models.FloatField(null=True),
        ),
    ]
