# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0002_auto_20170109_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanovanje',
            name='st_sten',
        ),
    ]
