# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0003_remove_stanovanje_st_sten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanovanje',
            old_name='temp_primanlkjaj',
            new_name='temp_primankljaj',
        ),
    ]
