# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0005_auto_20170110_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paneli',
            old_name='user',
            new_name='soba',
        ),
        migrations.RemoveField(
            model_name='paneli_tip',
            name='user',
        ),
    ]
