# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0006_auto_20170110_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneli',
            name='moc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paneli_tip',
            name='moc',
            field=models.IntegerField(null=True),
        ),
    ]
