# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irfoton_web', '0009_soba_namembnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soba',
            name='zun_stene',
            field=models.IntegerField(null=True),
        ),
    ]
